Client/PRN231_Project_EnglishTest_Client/Models/Result.cs
using System;
using System.Collections.Generic;

namespace PRN231_Project_EnglishTest_Client.Models;

public partial class Result
{
    public int ResultId { get; set; }

    public int? UserId { get; set; }

    public int? TestId { get; set; }

    public double? Score { get; set; }

    public DateTime? StartAt { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public virtual ICollection<ResultDetail> ResultDetails { get; set; } = new List<ResultDetail>();

    public virtual Test? Test { get; set; }

    public virtual User? User { get; set; }
}

Client/PRN231_Project_EnglishTest_Client/Controllers/ResultController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PRN231_Project_EnglishTest_Client.Dto.DoExam;
using PRN231_Project_EnglishTest_Client.Models;

namespace PRN231_Project_EnglishTest_Client.Controllers
{
    public class ResultController : Controller
    {
        public async Task<IActionResult> ResultPage(int resultid)
        {
            string link = "http://localhost:5166/api/Result/" + resultid.ToString();
            using (HttpClient client = new HttpClient())
            {
                using (HttpResponseMessage res = await client.GetAsync(link))
                {
                    if (res.IsSuccessStatusCode)
                    {
                        using (HttpContent content = res.Content)
                        {
                            string result1 = await content.ReadAsStringAsync();
                            Result result = JsonConvert.DeserializeObject<Result>(result1);
                            var usersession = HttpContext.Session.GetString("Userid") == null ? "0" : HttpContext.Session.GetString("Userid");

                            if (result == null)
                            {
                                return RedirectToAction("Error", "Home");
                            }
                            else
                            {
                                if (!result.UserId.ToString().Equals(usersession))
                                {
                                    return RedirectToAction("Error", "Home");
                                }

                                ViewBag.Result = result;
                                return View();
                            }
                        }
                    }
                    else
                    {
                        return RedirectToAction("Error", "Home");
                    }
                }
            }
        }
    }
}

Client/PRN231_Project_EnglishTest_Client/Controllers/ResultDetailController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PRN231_Project_EnglishTest_Client.DTO.ReviewPage;
using PRN231_Project_EnglishTest_Client.Models;

namespace PRN231_Project_EnglishTest_Client.Controllers
{
    public class ResultDetailController : Controller
    {
        public async Task<IActionResult> IndexAsync(int? resultid, int userid)
        {
            var role = HttpContext.Session.GetString("Role") == null ? "0" : HttpContext.Session.GetString("Role");
            var usersession = HttpContext.Session.GetString("Userid") == null ? "0" : HttpContext.Session.GetString("Userid");
            if ((!role.Equals("1") && !usersession.Equals(userid.ToString())) || usersession.Equals("0"))
            {
                return RedirectToAction("Error", "Home");
            }

            string link = "http://localhost:5166/api/ResultDetail/ResultDetailById/" + resultid;
            using (HttpClient client = new HttpClient())
            {
                using (HttpResponseMessage res = await client.GetAsync(link))
                {
                    if (res.IsSuccessStatusCode)
                    {
                        using (HttpContent content = res.Content)
                        {
                            string result = await content.ReadAsStringAsync();
                            List<ReviewPageDto> rv = JsonConvert.DeserializeObject<List<ReviewPageDto>>(result);
                            ViewBag.Detail = rv;

                            return View();
                        }
                    }
                    else
                    {
                        return RedirectToAction("Error", "Home");
                    }
                }
            }
        }
    }
}

Client/PRN231_Project_EnglishTest_Client/Views/Result/ResultPage.cshtml
@using PRN231_Project_EnglishTest_Client.Models
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@{
    Layout = "/Pages/Shared/_Layout.cshtml";
    Result res = ViewBag.Result;
}

@section content{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <div class="container mt-4">
        <h2>Exam Result</h2>
        <table class="table">
            <tbody>
                <tr>
                    <th scope="row">Score:</th>
                    <td>@res.Score</td>
                </tr>
                <tr>
                    <th scope="row">StartAt:</th>
                    <td>@res.StartAt</td>
                </tr>
                <tr>
                    <th scope="row">SubmittedAt:</th>
                    <td>@res.SubmittedAt</td>
                </tr>
                <tr>
                    <th scope="row">Review:</th>
                    <td>
                        <!-- Thêm nút Review và đặt ID cho nút để thực hiện hành động từ JavaScript -->
                        <a asp-action="Index" asp-controller="ResultDetail" asp-route-resultid="@res.ResultId" asp-route-userid="@res.UserId" id="btnReview" class="btn btn-primary">Review</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
}