Client/PRN231_Project_EnglishTest_Client/Controllers/HistoryAdminController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PRN231_Project_EnglishTest_Client.DTO.AdminHis;
using PRN231_Project_EnglishTest_Client.Models;

namespace PRN231_Project_EnglishTest_Client.Controllers
{
    public class HistoryAdminController : Controller
    {
        public async Task<IActionResult> IndexAsync()
        {
            var role = HttpContext.Session.GetString("Role") == null ? "0" : HttpContext.Session.GetString("Role");
            if (!role.Equals("1"))
            {
                return RedirectToAction("Error", "Home");
            }

            string link = "http://localhost:5166/api/Test";
            using (HttpClient client = new HttpClient())
            {
                using (HttpResponseMessage res = await client.GetAsync(link))
                {
                    if (res.IsSuccessStatusCode)
                    {
                        using (HttpContent content = res.Content)
                        {
                            string result = await content.ReadAsStringAsync();
                            List<Test> test = JsonConvert.DeserializeObject<List<Test>>(result);
                            ViewBag.Tests = test;
                            return View();
                        }
                    }
                    else
                    {
                        return RedirectToAction("Error", "Home");
                    }
                }
            }
        }

        public async Task<IActionResult> AdminHis(int testid)
        {
            HttpContext.Session.SetString("testidchart", testid.ToString());
            var role = HttpContext.Session.GetString("Role") == null ? "0" : HttpContext.Session.GetString("Role");
            if (!role.Equals("1"))
            {
                return RedirectToAction("Error", "Home");
            }

            string link = "http://localhost:5166/api/Result/AdminHis/" + testid;
            using (HttpClient client = new HttpClient())
            {
                using (HttpResponseMessage res = await client.GetAsync(link))
                {
                    if (res.IsSuccessStatusCode)
                    {
                        using (HttpContent content = res.Content)
                        {
                            string result = await content.ReadAsStringAsync();
                            List<AdminHisDto> adminHis = JsonConvert.DeserializeObject<List<AdminHisDto>>(result);
                            ViewBag.His = adminHis;
                            return View();
                        }
                    }
                    else
                    {
                        return RedirectToAction("Error", "Home");
                    }
                }
            }
        }
    }
}

Client/PRN231_Project_EnglishTest_Client/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PRN231_Project_EnglishTest_Client.Dto;
using PRN231_Project_EnglishTest_Client.Models;

namespace PRN231_Project_EnglishTest_Client.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> PostLoginAsync(string email, string password)
        {
            LoginDto login = new LoginDto
            {
                Email = email,
                Password = password
            };

            string link = "http://localhost:5166/api/Users/Login";
            using (HttpClient client = new HttpClient())
            {
                using (HttpResponseMessage res = await client.PostAsJsonAsync(link, login))
                {
                    if (res.IsSuccessStatusCode)
                    {
                        using (HttpContent content = res.Content)
                        {
                            string result = await content.ReadAsStringAsync();
                            User user = JsonConvert.DeserializeObject<User>(result);


                            // Lưu thông tin user vào Session
                            HttpContext.Session.SetString("Username", user.Username);
                            HttpContext.Session.SetString("Userid", user.UserId.ToString());
                            HttpContext.Session.SetString("Role", user.RoleId.ToString());

                            return RedirectToAction("Index", "Home");
                        }

                    }
                    else
                    {
                        TempData["login"] = "Login fail pls try again!";
                        return RedirectToAction("Index");
                    }
                }
            }
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }
    }
}

Client/PRN231_Project_EnglishTest_Client/Controllers/ResultHistoryController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PRN231_Project_EnglishTest_Client.DTO.ResultHistory;
using PRN231_Project_EnglishTest_Client.DTO.ReviewPage;

namespace PRN231_Project_EnglishTest_Client.Controllers
{
    public class ResultHistoryController : Controller
    {
        public async Task<IActionResult> IndexAsync(int? userid, int? testid)
        {
            var role = HttpContext.Session.GetString("Role") == null ? "0" : HttpContext.Session.GetString("Role");
            var usersession = HttpContext.Session.GetString("Userid") == null ? "0" : HttpContext.Session.GetString("Userid");
            if (!role.Equals("1") && !usersession.Equals(userid.ToString()))
            {
                return RedirectToAction("Error", "Home");
            }

            string link = "http://localhost:5166/api/Result/GetByUserId/" + userid;
            using (HttpClient client = new HttpClient()) 
            {
                using (HttpResponseMessage res = await client.GetAsync(link))
                {
                    if (res.IsSuccessStatusCode)
                    {
                        using (HttpContent content = res.Content)
                        {
                            string result = await content.ReadAsStringAsync();
                            List<ResultHistory> rh = JsonConvert.DeserializeObject<List<ResultHistory>>(result);
                            
                            if (testid != null)
                            {
                                rh = rh.Where(x => x.Testid == testid).ToList();
                            }
                            ViewBag.ResultHistory = rh;
                            return View();
                        }
                    }
                    else
                    {
                        return RedirectToAction("Error", "Home");
                    }
                }
            }
        }
    }
}

Client/PRN231_Project_EnglishTest_Client/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>English Test</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="shortcut icon" type="image/png" href="~/images/logos/favicon.png" />
    <link rel="stylesheet" href="~/css/styles.min.css" />
</head>
<body>



    <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
         data-sidebar-position="fixed" data-header-position="fixed">
        <aside class="left-sidebar">
            <div>
                <div class="brand-logo d-flex align-items-center justify-content-between">
                    <a asp-controller="Home" asp-action="Index" class="text-nowrap logo-img">
                        <img src="~/images/logos/dark-logo.png" width="180" alt="" />
                    </a>
                    <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
                        <i class="ti ti-x fs-8"></i>
                    </div>
                </div>
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
                    <ul id="sidebarnav">
                        <li class="nav-small-cap">
                            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                            <span class="hide-menu">Home</span>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link" asp-controller="Home" asp-action="Index" aria-expanded="false">
                                <span>
                                    <i class="ti ti-layout-dashboard"></i>
                                </span>
                                <span class="hide-menu">Dashboard</span>
                            </a>
                        </li>
                        @if (("1").Equals(Context.Session.GetString("Role")))
                        {
                            <li class="nav-small-cap">
                                <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                                <span class="hide-menu">Results</span>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" asp-controller="ResultHistory" asp-action="Index" aria-expanded="false" asp-route-userid="@int.Parse(Context.Session.GetString("Userid"))">
                                    <span>
                                        <i class="ti ti-article"></i>
                                    </span>
                                    <span class="hide-menu">Results History</span>
                                </a>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" asp-controller="HistoryAdmin" aria-expanded="false" asp-action="Index">
                                    <span>
                                        <i class="ti ti-article"></i>
                                    </span>
                                    <span class="hide-menu">Student's Exam History'</span>
                                </a>
                            </li>

                            <li class="nav-small-cap">
                                <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                                <span class="hide-menu">Manager</span>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" asp-controller="AllTest" aria-expanded="false" asp-action="Index">
                                    <span>
                                        <i class="ti ti-file-description"></i>
                                    </span>
                                    <span class="hide-menu">Test Management</span>
                                </a>
                            </li>
                            @*<li class="sidebar-item">
                                <a class="sidebar-link" asp-controller="AllTest" aria-expanded="false" asp-action="Detail">
                                    <span>
                                        <i class="ti ti-file-description"></i>
                                    </span>
                                    <span class="hide-menu">Question Management</span>
                                </a>
                            </li>*@

                        }
                        @if (("3").Equals(Context.Session.GetString("Role")))
                        {
                            <li class="nav-small-cap">
                                <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                                <span class="hide-menu">Results</span>
                            </li>
                            <li class="sidebar-item">
                                <a class="sidebar-link" asp-controller="ResultHistory" asp-action="Index" aria-expanded="false" asp-route-userid="@int.Parse(Context.Session.GetString("Userid"))">
                                    <span>
                                        <i class="ti ti-article"></i>
                                    </span>
                                    <span class="hide-menu">Results History</span>
                                </a>
                            </li>
                        }

            </div>
        </aside>

        <div class="body-wrapper">
            <header class="app-header">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <ul class="navbar-nav">
                        <li class="nav-item d-block d-xl-none">
                            <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                                <i class="ti ti-menu-2"></i>
                            </a>
                        </li>

                    </ul>
                    <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
                        <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">

                            <li class="nav-item dropdown">
                                <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                                   aria-expanded="false">
                                    <img src="~/images/profile/user-1.jpg" alt="" width="35" height="35" class="rounded-circle">
                                </a>
                                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                                    <div class="message-body">
                                        @if (Context.Session.GetString("Username") != null)
                                        {

                                            <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                                <i class="ti ti-user fs-6"></i>
                                                <p class="mb-0 fs-3">My Profile</p>
                                            </a>
                                            <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                                <i class="ti ti-mail fs-6"></i>
                                                <p class="mb-0 fs-3">My Account</p>
                                            </a>
                                            <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                                <i class="ti ti-list-check fs-6"></i>
                                                <p class="mb-0 fs-3">My Task</p>
                                            </a>
                                            <a class="btn btn-outline-primary mx-3 mt-2 d-block" asp-controller="Login" asp-action="Logout">(@Context.Session.GetString("Username")) Logout</a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-outline-primary mx-3 mt-2 d-block" asp-controller="Login" asp-action="Index">Login</a>
                                        }



                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>

            <div class="container-fluid">
                <main role="main" class="pb-3">
                    @RenderSection("content", required: false)
                </main>
            </div>

        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>